// Generated by scripts/generate-env.js
(function () {
  const configured = ''.trim();
  const host = window.location.hostname || '';
  const isLocal = /^(localhost|127\.0\.0\.1|::1)$/.test(host);
  window.__API_BASE__ = configured || (isLocal ? 'http://localhost:8000' : '');
})();

(function () {
  try {
    const base = (window.__API_BASE__ || '').replace(/\/$/, '');
    document.addEventListener('DOMContentLoaded', () => {
      const els = document.querySelectorAll('a.nav-docs');
      els.forEach((a) => {
        if (base) a.href = base + '/docs';
        else a.style.display = 'none';
      });
      const docsLink = document.getElementById('api-docs-link');
      if (docsLink && base) docsLink.href = base + '/docs';
    });
  } catch (e) {}
})();
