const fs = require('fs');
const path = require('path');

// Usage: set API_BASE env var, e.g.
// API_BASE=https://your-api.onrender.com node scripts/generate-env.js

const apiBase = (process.env.API_BASE || '').trim();
const safeApiBase = apiBase.replace(/'/g, "\\'");
const out = `// Generated by scripts/generate-env.js
(function () {
  const configured = '${safeApiBase}'.trim();
  const host = window.location.hostname || '';
  const isLocal = /^(localhost|127\\.0\\.0\\.1|::1)$/.test(host);
  window.__API_BASE__ = configured || (isLocal ? 'http://localhost:8000' : '');
})();

(function () {
  try {
    const base = (window.__API_BASE__ || '').replace(/\\/$/, '');
    document.addEventListener('DOMContentLoaded', () => {
      const els = document.querySelectorAll('a.nav-docs');
      els.forEach((a) => {
        if (base) a.href = base + '/docs';
        else a.style.display = 'none';
      });
      const docsLink = document.getElementById('api-docs-link');
      if (docsLink && base) docsLink.href = base + '/docs';
    });
  } catch (e) {}
})();
`;
const target = path.join(__dirname, '..', 'frontend', 'env.js');
fs.writeFileSync(target, out, 'utf8');
console.log(`Wrote ${target} with API_BASE=${apiBase}`);
